---
driver:
  name: vagrant

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: ubuntu64
    driver_config:
      box: ubuntu/trusty64
      gui: true

suites:
  - name: default
    run_list:
      - recipe[simple_slack_handler::default]
    attributes:
