name 'simple_slack_handler'
maintainer 'John Kerry'
maintainer_email 'john@kerryhouse.net'
license 'all_rights'
description 'Installs/Configures simple_slack_handler'
long_description 'Installs/Configures simple_slack_handler'
version '0.1.0'
issues_url 'https://github.com/jkerry/SimpleSlackHandler/issues'
source_url 'https://github.com/jkerry/SimpleSlackHandler'
depends 'chef_handler', '~> 2.0.0'
